export const UserActionTypes = {
  EMAIL_SIGN_UP_REQUEST: 'EMAIL_SIGN_UP_REQUEST',
  EMAIL_SIGN_UP_SUCCESS: 'EMAIL_SIGN_UP_SUCCESS',
  EMAIL_SIGN_UP_FAILURE: 'EMAIL_SIGN_UP_FAILURE',

  EMAIL_SIGN_IN_REQUEST: 'EMAIL_SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
};

export default UserActionTypes;